"""add model_artifact_id to production logs

Revision ID: 684485219520
Revises: f3c9a2d8b741
Create Date: 2026-07-12 04:16:34.319308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684485219520'
down_revision: Union[str, Sequence[str], None] = 'f3c9a2d8b741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_production_logs', sa.Column('model_artifact_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_daily_production_logs_model_artifact_id'), 'daily_production_logs', ['model_artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_production_logs_model_artifact_id'), table_name='daily_production_logs')
    op.drop_column('daily_production_logs', 'model_artifact_id')
    # ### end Alembic commands ###
