"""initial schema

Revision ID: 89176fa52d40
Revises: 
Create Date: 2026-05-17 10:06:37.591298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89176fa52d40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table('daily_production_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'DRAFT', 'ANOMALY', 'FAILED', 'RECONCILED', name='production_log_status'), server_default=sa.text("'PROCESSING'"), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('total_output_ton', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimasi_wip_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimasi_manual_class_b', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('estimasi_manual_reject', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('estimasi_prime', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('aktual_wip', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('aktual_prime', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('needs_retraining', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_production_logs_production_date'), 'daily_production_logs', ['production_date'], unique=True)
    op.create_index(op.f('ix_daily_production_logs_task_id'), 'daily_production_logs', ['task_id'], unique=False)
    op.create_table('daily_profile_details',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('detail_seq', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=120), nullable=False),
    sa.Column('raw_material_ton', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('production_ton', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gas_consumption_rolling_nm3', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('electricity_kv20_kwh', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('downtime_stand_change_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lower(profile_name) <> 'shutdown'", name='ck_profile_not_shutdown'),
    sa.ForeignKeyConstraint(['log_id'], ['daily_production_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id', 'detail_seq', name='uq_daily_profile_log_seq')
    )
    op.create_index(op.f('ix_daily_profile_details_log_id'), 'daily_profile_details', ['log_id'], unique=False)
    op.create_index(op.f('ix_daily_profile_details_profile_name'), 'daily_profile_details', ['profile_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_profile_details_profile_name'), table_name='daily_profile_details')
    op.drop_index(op.f('ix_daily_profile_details_log_id'), table_name='daily_profile_details')
    op.drop_table('daily_profile_details')
    op.drop_index(op.f('ix_daily_production_logs_task_id'), table_name='daily_production_logs')
    op.drop_index(op.f('ix_daily_production_logs_production_date'), table_name='daily_production_logs')
    op.drop_table('daily_production_logs')
    op.execute("DROP TYPE IF EXISTS production_log_status")
    # ### end Alembic commands ###
