"""update profile detail features

Revision ID: ebbc15959847
Revises: 89176fa52d40
Create Date: 2026-06-02 22:37:50.278568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbc15959847'
down_revision: Union[str, Sequence[str], None] = '89176fa52d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_profile_details', sa.Column('material_pcs', sa.Integer(), nullable=False))
    op.add_column('daily_profile_details', sa.Column('production_pcs', sa.Integer(), nullable=False))
    op.add_column('daily_profile_details', sa.Column('total_hrs', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('availables_hrs', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('setup_time', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('program_stop_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('stand_change', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('production_stop_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('mechanic_stop_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('electric_stop_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('roll_shop_stop_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('test_rolling_stop_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('trial_rolling_stop_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('others_stop_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('downtime_total_min', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('rolling_hot_hrs', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('idle_hrs', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('rolling_hrs', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('gas_total_day_nm3', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('kv_20', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('kv_33', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('electricity_total_kwh', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('daily_profile_details', sa.Column('predicted_wip_ton', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('daily_profile_details', sa.Column('actual_wip_ton', sa.Numeric(precision=14, scale=2), nullable=True))
    op.alter_column('daily_profile_details', 'raw_material_ton',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('daily_profile_details', 'production_ton',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.create_unique_constraint('uq_daily_profile_log_profile', 'daily_profile_details', ['log_id', 'profile_name'])
    op.drop_column('daily_profile_details', 'gas_consumption_rolling_nm3')
    op.drop_column('daily_profile_details', 'downtime_stand_change_min')
    op.drop_column('daily_profile_details', 'electricity_kv20_kwh')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_profile_details', sa.Column('electricity_kv20_kwh', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('daily_profile_details', sa.Column('downtime_stand_change_min', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('daily_profile_details', sa.Column('gas_consumption_rolling_nm3', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint('uq_daily_profile_log_profile', 'daily_profile_details', type_='unique')
    op.alter_column('daily_profile_details', 'production_ton',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('daily_profile_details', 'raw_material_ton',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.drop_column('daily_profile_details', 'actual_wip_ton')
    op.drop_column('daily_profile_details', 'predicted_wip_ton')
    op.drop_column('daily_profile_details', 'electricity_total_kwh')
    op.drop_column('daily_profile_details', 'kv_33')
    op.drop_column('daily_profile_details', 'kv_20')
    op.drop_column('daily_profile_details', 'gas_total_day_nm3')
    op.drop_column('daily_profile_details', 'rolling_hrs')
    op.drop_column('daily_profile_details', 'idle_hrs')
    op.drop_column('daily_profile_details', 'rolling_hot_hrs')
    op.drop_column('daily_profile_details', 'downtime_total_min')
    op.drop_column('daily_profile_details', 'others_stop_min')
    op.drop_column('daily_profile_details', 'trial_rolling_stop_min')
    op.drop_column('daily_profile_details', 'test_rolling_stop_min')
    op.drop_column('daily_profile_details', 'roll_shop_stop_min')
    op.drop_column('daily_profile_details', 'electric_stop_min')
    op.drop_column('daily_profile_details', 'mechanic_stop_min')
    op.drop_column('daily_profile_details', 'production_stop_min')
    op.drop_column('daily_profile_details', 'stand_change')
    op.drop_column('daily_profile_details', 'program_stop_min')
    op.drop_column('daily_profile_details', 'setup_time')
    op.drop_column('daily_profile_details', 'availables_hrs')
    op.drop_column('daily_profile_details', 'total_hrs')
    op.drop_column('daily_profile_details', 'production_pcs')
    op.drop_column('daily_profile_details', 'material_pcs')
    # ### end Alembic commands ###
